apiVersion: v1
kind: ServiceAccount

metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::762233727039:role/external-secrets-role