apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: ps-backend-external-secret
  namespace: backend

spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: ps-cluster-secret-store
    kind: ClusterSecretStore
  
  target:
    name: ps-backend-secret
    creationPolicy: Owner
  
  data:
    - secretKey: DB_URL
      remoteRef:
        key: /educonnect/backend/db_url