apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: sm-backend-external-secret
  namespace: backend

spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: sm-cluster-secret-store
    kind: ClusterSecretStore
  
  target:
    name: sm-backend-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: educonnect/backend
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: educonnect/backend
        property: DB_PASSWORD
    - secretKey: GMAIL_PASSWORD
      remoteRef:
        key: educonnect/backend
        property: GMAIL_PASSWORD