apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: aws-load-balancer-controller-app

spec:
  project: default

  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.7.1
  
    helm:
      values: |
        clusterName: edu-cluster
        region: us-east-1
        vpcId: vpc-0ce917278d770499f
        serviceAccount.create: false
        serviceAccount.name: aws-load-balancer-controller
        fullnameOverride: aws-load-balancer-controller

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    syncOptions:
      - CreateNamespace=true